### ISSUE TITLE
Will it support 64-128KB save?

### ISSUE THREAD

**Issue by MelonGx** [HDR/MBC30-Flashcart#1]
Since original Crystal JP is 64KB save.

**Comment by HDR** [comment]
The carts will support up to 256 Kbit, there is no suitable 5V fram that is bigger than this.

https://www.infineon.com/dgdl/Infineon-FM18W08_256-Kbit_(32_K_8)_Wide_Voltage_Bytewide_F-RAM_Memory-DataSheet-v06_00-EN.pdf?fileId=8ac78c8c7d0d8da4017d0ec89b424117
